---
title: "Práctica de uso del paquete dplyr"
author: "Nayely Araya"
format: html
toc: true
lang: es
theme: yeti
---

# Introducción
Este documento contiene algunos ejemplos de uso de las funciones del paquete dplyr de [Tidyverse](https://www.tidyverse.org/)

# Carga de paquetes

```{r}
#| label: carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(palmerpenguins)
library(knitr)
```

# Carga de datos

```{r}
#| label: carga-datos
#| message: false
#| warning: false

delitos_2023 <- read_csv("estadisticaspoliciales2023.csv",
                         locale = locale(encoding = "WINDOWS-1252"))
```

# select()

## Ejemplo 1

```{r}
#| label: select-1

# select (penguins, species, bill_length_mm, sex)

penguins |>
  select(species, bill_length_mm, sex) |>
  head(10) |>
  kable()
```

## Ejemplo 2

```{r}
#| label: select-2

penguins |>
  select(especie = species,
         longitud_pico_mm = bill_length_mm,
         sexo = sex) |>
  head(10) |>
  kable()
```

# filter()

## Ejemplo 1

```{r}
#| label: filter-1

penguins |>
  select(species, island, sex) |>
  filter(species == "Adelie" & sex == "male" 
         & island == "Torgersen") |>
  kable()
```

## Ejemplo 2

```{r}
#| label: filter-2

#Delitos del cantón de Montes de Oca

delitos_2023 |>
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  filter(Canton == "MONTES DE OCA" & Victima == "VEHICULO") |>
  kable()
```

## Ejemplo 3

```{r}
#| label: filter-3

#Asaltos cometidos en San Pedro de Montes de Oca

delitos_2023 |>
select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  filter(Distrito == "SAN PEDRO" & Canton == "MONTES DE OCA" & Delito == "ASALTO") |>
  kable()
```

## Ejemplo 4

```{r}
#| label: filter-4

#Asaltos y homicidios cometidos en San Pedro de Montes de Oca

delitos_2023 |>
select(Delito, Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  filter((Distrito == "SAN PEDRO" & 
           Canton == "MONTES DE OCA") & 
           (Delito == "ASALTO" | Delito == "HOMICIDIO")) |>
  kable()
```

# Arrange ()

## Ejemplo 1

```{r}
#| label: arrange-1

penguins |>
  select(species, bill_length_mm, bill_depth_mm) |>
  head(12) |>
  arrange(desc(bill_length_mm), bill_depth_mm) |>
  kable()
```

# Mutate ()

## Ejemplo 1

```{r}
#| label: mutate-1

penguins |>
  select(species, sex, body_mass_g) |>
  mutate(body_mass_kg = body_mass_g / 1000) |>
  head(12) |>
  kable()
```

## Ejemplo 2 

```{r}
#| label: mutate-2

penguins |>
  select(species, sex, body_mass_g) |>
  mutate(body_mass_kg = body_mass_g / 1000,
         body_mass_lb = body_mass_kg * 2.2) |>
  head(12) |>
  kable()
```

## Ejemplo 3

```{r}
#| label: mutate-3

delitos_2023 |>
  select(Delito, SubDelito, Fecha, Hora, Canton) |>
  mutate(Fecha_Date = as.Date(delitos_2023$Fecha, format = "%d/%m/%Y")) |>
  filter(Canton == "MONTES DE OCA") |>
  arrange(Fecha) |>
  kable()
```

# Summarize()

## Ejemplo 1

```{r}
#| label: summarize-1

# Peso promedio por especie de pingüinos

penguins |>
  group_by(species) |>
  summarize(
    body_mass_g_mean = mean(body_mass_g, na.rm = TRUE),
    body_mass_g_min = min(body_mass_g, na.rm = TRUE),
    body_mass_g_max = max(body_mass_g, na.rm = TRUE)) |>
  kable()
```

```{r}
#| label: aggregate-1

aggregate(
  body_mass_g ~ species,
  data = penguins,
  FUN = mean
)
```

## Ejemplo 2

```{r}
#| label: summarize-2

# Cantidad de homicidios por provincia y cantón


delitos_2023 |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Provincia, Canton, Distrito) |>
  summarize(homicidios_2023 = n()) |>
  arrange(desc(homicidios_2023)) |>
  kable()
```

## Ejemplo 3

```{r}
#| label: summarize-3

delitos_2023 |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Genero) |>
  summarize(n = n()) |>
  kable()
```

## Ejemplo 4

```{r}
#| label: summarize-4

delitos_2023 |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Nacionalidad) |>
  summarize(n = n()) |>
  arrange(desc(n)) |>
  kable()
```

## Ejemplo 5

```{r}
#| label: summarize-5

#Promedio de masa y n cantidad de registros de pingüinos
penguins |>
  summarize(body_mass_g_mean = mean(body_mass_g, na.rm = TRUE), n = n()) |>
  kable()
```






